# Generated by Django 3.2.13 on 2022-07-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0045_auto_20220725_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassenrollment',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liveclassenrollment_assigned_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveclassenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassenrollment_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
