<<<<<<< HEAD
name: CI
=======
name: Migrations check on MySql 57
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_migrations:
    name: check migrations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
<<<<<<< HEAD
        os: [ ubuntu-18.04 ]
=======
        os: [ ubuntu-20.04 ]
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
        python-version: [ 3.8 ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev

    - name: Get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/development.txt') }}
        restore-keys: ${{ runner.os }}-pip-

<<<<<<< HEAD
=======
    - name: Install MySQL 5.7
      run: |
        mkdir ${RUNNER_WORKSPACE}/mysql_packages && cd ${RUNNER_WORKSPACE}/mysql_packages
        sudo apt-get remove --purge *mysql* -y
        sudo rm -rvf /etc/init.d/mysql* /etc/mysql* /var/lib/mysql*
        sudo apt-get install libaio1 libnuma1 libtinfo5 -y
        wget https://cdn.mysql.com/archives/mysql-5.7/mysql-server_5.7.35-1ubuntu18.04_amd64.deb-bundle.tar
        tar -xf mysql-server_5.7*.tar
        sudo DEBIAN_FRONTEND=noninteractive dpkg --install mysql-common_5.7*.deb libmysqlclient*.deb mysql-server_5.7*.deb mysql-client_5.7*.deb mysql-community-server_5.7*.deb mysql-community-client_5.7*.deb

    - name: Ubuntu and sql Versions
      run: |
        lsb_release -a
        mysql -V

>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
    - name: Install Python dependencies
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/edx/development.txt
        pip uninstall -y mysqlclient
        pip install --no-binary mysqlclient mysqlclient
        pip uninstall -y xmlsec
        pip install --no-binary xmlsec xmlsec

    - name: Initiate Services
      run: |
        sudo systemctl start mongod
        sudo /etc/init.d/mysql start

    - name: Reset mysql password
      run: |
<<<<<<< HEAD
        cat <<EOF | mysql -h 127.0.0.1 -u root --password=root
=======
        cat <<EOF | sudo mysql -u root
          UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE user = 'root';
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
          UPDATE mysql.user SET authentication_string = null WHERE user = 'root';
          FLUSH PRIVILEGES;
        EOF

    - name: Run Tests
      env:
        LMS_CFG: lms/envs/bok_choy.yml
      run: |
<<<<<<< HEAD
        echo "CREATE DATABASE IF NOT EXISTS edxtest;" | mysql -u root
        echo "CREATE DATABASE IF NOT EXISTS student_module_history_test;" | mysql -u root
=======
        echo "CREATE DATABASE IF NOT EXISTS edxtest;" | sudo mysql -u root
        echo "CREATE DATABASE IF NOT EXISTS student_module_history_test;" | sudo mysql -u root
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38

        echo "Running the LMS migrations."
        ./manage.py lms --settings bok_choy migrate
        echo "Running the CMS migrations."
        ./manage.py cms --settings bok_choy migrate
