<<<<<<< HEAD
name: CI
=======
name: Quality checks
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38

on:
  pull_request:
  push:
    branches:
      - master
      - open-release/lilac.master

jobs:
  run_tests:
    name: Quality Others
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]
<<<<<<< HEAD
        node-version: [ 12 ]

=======
        node-version: [ 16 ]
        
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

<<<<<<< HEAD
    - name: Fetch master for comparison
=======
    - name: Fetch base branch for comparison
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
      run: git fetch --depth=1 origin ${{ github.base_ref }}

    - name: Install Required System Packages
      run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

<<<<<<< HEAD
=======
    - name: Setup npm
      run: npm i -g npm@8.5.x

>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
    - name: Get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/testing.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install Required Python Dependencies
      env:
        PIP_SRC_DIR: ${{ runner.temp }}
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/edx/testing.txt -r requirements/edx/django.txt --src $PIP_SRC_DIR

    - name: Run Quality Tests
      env:
        TEST_SUITE: quality
        SCRIPT_TO_RUN: ./scripts/generic-ci-tests.sh
        SHARD: 4
        PIP_SRC_DIR: ${{ runner.temp }}
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        ./scripts/all-tests.sh

    - name: Save Job Artifacts
<<<<<<< HEAD
=======
      if: always()
>>>>>>> 295cf4fc64a17ee2e01e062ad782fcbe7b514c38
      uses: actions/upload-artifact@v2
      with:
        name: Build-Artifacts
        path: |
          **/reports/**/*
          test_root/log/**/*.log
          *.log
